package pl.boardgame.duckburg.deck.cards.types;

public class CardNames {

	public static final String TOWNHALL_1 = "Mayor";
	public static final String TOWNHALL_2 = "ElectricalEmergency";
	public static final String TOWNHALL_3 = "GasEmergency";
	public static final String TOWNHALL_4 = "ChemicalEmergency";
	public static final String TOWNHALL_5 = "Roadmen";
	public static final String TOWNHALL_6 = "TelephoneEmergency";
	public static final String TOWNHALL_7 = "PostOffice";
	public static final String TOWNHALL_8 = "Court";
	public static final String TOWNHALL_9 = "Prison";
	public static final String TOWNHALL_10 = "Barracks";

	public static final String POLICE_1 = "CarPatrol";
	public static final String POLICE_2 = "Antiterrorists";
	public static final String POLICE_3 = "MountedPatrol";
	public static final String POLICE_4 = "TrafficControl";
	public static final String POLICE_5 = "Detectives";
	public static final String POLICE_6 = "PoliceStation";
	public static final String POLICE_7 = "MotorcyclePatrol";

	public static final String FIREFIGHTER_1 = "FireStation";
	public static final String FIREFIGHTER_2 = "FireTruck";
	public static final String FIREFIGHTER_3 = "Firefighters";

	public static final String HEALTH_1 = "Dentist";
	public static final String HEALTH_2 = "Clinic";
	public static final String HEALTH_3 = "Sanatorium";
	public static final String HEALTH_4 = "Hospital";
	public static final String HEALTH_5 = "Ambulance";

	public static final String ENTERTAINMENT_1 = "Library";
	public static final String ENTERTAINMENT_2 = "Museum";
	public static final String ENTERTAINMENT_3 = "Circus";
	public static final String ENTERTAINMENT_4 = "Philharmonic";
	public static final String ENTERTAINMENT_5 = "Opera";
	public static final String ENTERTAINMENT_6 = "ConcertHall";
	public static final String ENTERTAINMENT_7 = "AmusementPark";
	public static final String ENTERTAINMENT_8 = "Park";
	public static final String ENTERTAINMENT_9 = "Zoo";
	public static final String ENTERTAINMENT_10 = "Casion";
	public static final String ENTERTAINMENT_11 = "Cinema";
	public static final String ENTERTAINMENT_12 = "Theatre";

	public static final String ECONOMY_1 = "Factory";
	public static final String ECONOMY_2 = "Greenhouse";
	public static final String ECONOMY_3 = "Sawmill";
	public static final String ECONOMY_4 = "Farm";
	public static final String ECONOMY_5 = "Rafinery";
	public static final String ECONOMY_6 = "PrintingHouse";
	public static final String ECONOMY_7 = "Ironworks";
	public static final String ECONOMY_8 = "School";
	public static final String ECONOMY_9 = "HighSchool";
	public static final String ECONOMY_10 = "University";
	public static final String ECONOMY_11 = "Kindergarten";
	public static final String ECONOMY_12 = "ScientificInstitute";

	public static final String SERVICES_1 = "GroceryStore";
	public static final String SERVICES_2 = "Chemists";
	public static final String SERVICES_3 = "TravelAgency";
	public static final String SERVICES_4 = "Bookstore";
	public static final String SERVICES_5 = "ClothesShop";
	public static final String SERVICES_6 = "ElectronicShop";
	public static final String SERVICES_7 = "Florist";
	public static final String SERVICES_8 = "CarDealer";
	public static final String SERVICES_9 = "Restaurant";
	public static final String SERVICES_10 = "Cafe";
	public static final String SERVICES_11 = "TvStation";
	public static final String SERVICES_12 = "RadioStation";
	public static final String SERVICES_13 = "ComputerService";
	public static final String SERVICES_14 = "Bank";
	public static final String SERVICES_15 = "TransportCompany";
	public static final String SERVICES_16 = "ConstructionCompany";
	public static final String SERVICES_17 = "Hairdresser";
	public static final String SERVICES_18 = "Bakery";
	public static final String SERVICES_19 = "Tailor";
	public static final String SERVICES_20 = "Carpenter";
	public static final String SERVICES_21 = "Shoemaker";
	public static final String SERVICES_22 = "Glazier";
	public static final String SERVICES_23 = "ChimneySweep";

	public static final String SPORT_1 = "Pool";
	public static final String SPORT_2 = "FootballStadium";
	public static final String SPORT_3 = "BasketballField";
	public static final String SPORT_4 = "TennisCort";
	public static final String SPORT_5 = "HorseRacing";
	public static final String SPORT_6 = "SportStadium";
	public static final String SPORT_7 = "Rink";
	public static final String SPORT_8 = "Skatepark";
	public static final String SPORT_9 = "SportHall";
	public static final String SPORT_10 = "FrogRacing";

	public static final String TRANSPORT_1 = "Taxi";
	public static final String TRANSPORT_2 = "CityBus";
	public static final String TRANSPORT_3 = "TrainStation";
	public static final String TRANSPORT_4 = "MetroStation";
	public static final String TRANSPORT_5 = "Airport";
	public static final String TRANSPORT_6 = "Harbor";
	public static final String TRANSPORT_7 = "HorseCab";
	public static final String TRANSPORT_8 = "Helicopter";
	public static final String TRANSPORT_9 = "Balloon";
	public static final String TRANSPORT_10 = "SpaceStation";

	public static final String SPECIAL_1 = "ScroogeTreasury";
	public static final String SPECIAL_2 = "DonaldHouse";
	public static final String SPECIAL_3 = "DaisyHouse";
	public static final String SPECIAL_4 = "GyroGearlooseLaboratory";
	public static final String SPECIAL_5 = "GrannyHouse";
	public static final String SPECIAL_6 = "BeagleBoysHidehouse";
	public static final String SPECIAL_7 = "ConerliusMonument";
	public static final String SPECIAL_8 = "EditorialOfficeDonald";
	public static final String SPECIAL_9 = "ScoutCamp";

	public static final String ACTION_1 = "WorldCup";
	public static final String ACTION_2 = "SpringHoliday";
	public static final String ACTION_3 = "PlagueOfRats";
	public static final String ACTION_4 = "Fire";
	public static final String ACTION_5 = "Flood";
	public static final String ACTION_6 = "Hurricane";
	public static final String ACTION_7 = "Earthquake";
	public static final String ACTION_8 = "TimeMachine";
	public static final String ACTION_9 = "StockMarketCrash";
	public static final String ACTION_10 = "PrisonBreak";
	public static final String ACTION_11 = "UFO";
	public static final String ACTION_12 = "Carnival";
	public static final String ACTION_13 = "Elections";
	public static final String ACTION_14 = "Epidemic";
	public static final String ACTION_15 = "ScienceConvent";
	public static final String ACTION_16 = "SympatheticCup";
	public static final String ACTION_17 = "Investor";
	public static final String ACTION_18 = "Supermarket";
	public static final String ACTION_19 = "Collision";
	public static final String ACTION_20 = "Fireworks";
	public static final String ACTION_21 = "TownRebuild";
	public static final String ACTION_22 = "Spy";
	public static final String ACTION_23 = "MayorDoppelganger";
	public static final String ACTION_24 = "BoredomEpidemic";
	public static final String ACTION_25 = "Olympics";
	public static final String ACTION_26 = "FuelCrisis";
	public static final String ACTION_27 = "WitchArrival";
	public static final String ACTION_28 = "TrafficJam";
	public static final String ACTION_29 = "TerroristAttack";
	public static final String ACTION_30 = "BeagleBoysAttack";
	public static final String ACTION_31 = "PickpocketConvent";
	public static final String ACTION_32 = "MummyInvasion";
	public static final String ACTION_33 = "ElephantMedicine";
	public static final String ACTION_34 = "CarCrash";
	public static final String ACTION_35 = "DonaldsCar";
	public static final String ACTION_36 = "Burglar";
	public static final String ACTION_37 = "SnowFlurry";
	public static final String ACTION_38 = "Powerdown";
	public static final String ACTION_39 = "Mist";
	public static final String ACTION_40 = "StinkyBombExplosion";
	public static final String ACTION_41 = "TankerShipCrash";
	public static final String ACTION_42 = "LuckyDay";
	public static final String ACTION_44 = "TrollAttack";
	public static final String ACTION_45 = "Xmass";
	public static final String ACTION_46 = "TaxRaise";
	public static final String ACTION_47 = "OceanMerchantFleet";
	public static final String ACTION_48 = "SpyPlane";
	public static final String ACTION_49 = "CarRace";
	public static final String ACTION_50 = "Marathon";

}
